### ISSUE TITLE
Destination Ignored

### ISSUE THREAD

**Issue by crazydahveed** [jschicht/RawCopy#1]
In the current version of RawCopy (1.0.0.10), the destination path and file name are ignored.  Instead, the file is copied to the RawCopy directory with the original file name.  I have tried both relative and absolute file names to no avail.

Attempted command:
rawcopy-master\rawcopy.exe C:\Users\user\ntuser.dat test.dat
rawcopy-master\rawcopy.exe C:\Users\user\ntuser.dat C:\test.dat

Both results in the file being copied to rawcopy-master\ntuser.dat

Thanks!
David

**Comment by crazydahveed** [comment]
As a note, this wouldn't technically be a bug since the destination is supposed to be a folder.  However, it would be helpful to be able to specify a destination filename for things like copying all ntuser.dat files.

**Comment by lespea** [comment]
+1

**Comment by jschicht** [comment]
Feature was added in latest version 1.0.0.1.8.
