### ISSUE TITLE
Why does RawCopy ask for Administrator Privilege ?

### ISSUE THREAD

**Issue by AddaxSoft** [jschicht/RawCopy#12]
To my understanding if you have read access to the file, you don't need admin privs to copy it using rawcopy even if Windows protects that file, however, each time I run rawcopy it asks for admin privs by default.

**Comment by lespea** [comment]
https://support.microsoft.com/en-us/help/100027/info-direct-drive-access-under-win32

> You can open a physical or logical drive using the CreateFile() application programming interface (API) with these device names provided that you have the appropriate access rights to the drive (that is, you must be an administrator)

**Comment by jschicht** [comment]
Remember that you can read anything from the disk with those low level functions. If non-admin users were allowed to do this it would be a major security flaw. So, you need to be an admin user in order to run RawCopy successfully.
