### ISSUE TITLE
_GetIndexNumber function doesnt work on ntuser.dat?

### ISSUE THREAD

**Issue by ghost** [jschicht/RawCopy#14]
Copying ntuser.dat on windows 10 64 bit fails if file path is used, but works if index number is specified. It looks that _GetIndexNumber function returns error, but getting index number in this way works:

[Get Index Number.txt](https://github.com/jschicht/RawCopy/files/1130882/Get.Index.Number.txt)

**Comment by jschicht** [comment]
I had a look at your example, which seems to work fine. But I am wondering what is causing this issue, as I am not able to reproduce here on Windows 10 x64. Can you send me the exact commandline you supplied as well as the exact error message returned?

**Comment by jschicht** [comment]
The unused code that this relates to was removed in the version released yesterday. If the problem reappear on your end, please open another ticket with details on how to reproduce it.
