### ISSUE TITLE
Rawcopy and "soft" links

### ISSUE THREAD

**Issue by Beercow** [jschicht/RawCopy#16]
When I make a link to a different directory, rawcopy does not copy the whole file. 

Example:

mklink /d "c:\asset" "C:\"

rawcopy /FileNamePath:c:\asset\hiberfil.sys /OutputPath:c:\temp

The actual size of hiberfil.sys is 6,662,176 KB

The size of the copied hiberfil.sys is 467,456 KB

**Comment by jschicht** [comment]
I can confirm that bug. What happened is that rawcopy likely copied $MFT itself in that case. This kind of use was never accounted for, as it was meant to be used directly on the source like /filenamepath:c:\hiberfil.sys instead.
