### ISSUE TITLE
Checksum / hash of generated file is different

### ISSUE THREAD

**Issue by Noexpert** [jschicht/RawCopy#19]
Firstly, thanks for this great program.
I'm currently using it to copy Outlook pst files that are locked whist they are in use.

The files are copied correctly and when I look at the file size in Windows they are the same.

However when I check the files in Cygwin using `md5sum` and `openssl sha1` the results don't match.
Digging further using `cmp` I get the following message: `differ: byte 1758375937, line 5547995`.

So it seems the difference is small, but it's there.

Is this an issue?

Thanks

**Comment by ruchirarya** [comment]
Not sure exactly if this is an issue.
What if the original file changed at the runtime when RawCopy was copying the file at low level!?
Maybe try running multiple times with few seconds gap and see if the hashes are same!

**Comment by jschicht** [comment]
Could be a bug in another tool, or simply file content that has changed. If still a problem, please open a new issue.
