### ISSUE TITLE
Error in function CreateFile: Access is denied

### ISSUE THREAD

**Issue by mfran2002** [jschicht/RawCopy#22]
Hi,
I'm trying to copy a locked file (.ost) from a remote mapped folder P: (where outlook is running) to another mapped remote folder M: (NAS). Using this command:

RawCopy64.exe /FileNamePath:P:\mypath\myfile.ost /OutputPath:M:\NASpat /OutputName:myfile.ost

Error in function CreateFile: Access is denied. for \\.\P:

what i'm doing wrong?
thanks

**Comment by n3l5** [comment]
RawCopy isn't for copying from remote/mapped drives; it is for pulling "raw" files from local filesystem volumes.
