### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by jmmicmc** [jschicht/RawCopy#5]
Does rawcopy work in Windows 10?

James

**Comment by lespea** [comment]
I haven't had any problems so far

**Comment by jmmicmc** [comment]
Mine says Error: File probably locked. The directory I want to backup is a directory of DBF files that are being controlled by the Codebase database manager.

**Comment by jmmicmc** [comment]
If I leave the /full parameter out I get this message:

Error: File not found in Param1: c:\embs\data\data
Error: NtOpenFile returned: 0xC000003A
Opening target file failed, now re-trying with INDX method from parent folder
Error: Cannot get IndexNumber of parent folder: c:\embs\data

**Comment by jschicht** [comment]
It was only meant to copy individual files. Not directories.

**Comment by jmmicmc** [comment]
I see that now. Well I have to make a long batch file to copy all the files! Thanks though.
