### ISSUE TITLE
Cannot execute in WINDOWS2000

### ISSUE THREAD

**Issue by WindoC** [jschicht/RawCopy#6]
RawCopy not able to execute in Windows2000. It show "RawCopy.exe is not a valid Win32 application."

**Comment by jschicht** [comment]
This could have to be about how the executable is compiled. You could try changing 2 fields in the Optional Header, named MajorOperatingSystemVersion and MajorSubsystemVersion. See attachment. 
![rawcopy](https://cloud.githubusercontent.com/assets/6486883/14618684/18d437f8-05b4-11e6-9173-b9777c014db7.PNG)
Nice tool to use is CFF Explorer.
However, if even if that tricks works to load the program, it was never tested on that Windows version. I have no guarantee that it will work. But please test and report back.

**Comment by slaswi** [comment]
Unfortunately this does not help.

![image](https://cloud.githubusercontent.com/assets/28098674/25482010/2224240e-2b50-11e7-8fd0-aa4ded270226.png)

**Comment by jschicht** [comment]
Unfortunately I don't have Windows 2000 to test this on. If you send me an email on joakim.schicht@gmail.com I might create something for you to test if interested.

**Comment by daverstephens** [comment]
The function IcmpSendEcho is in icmp.dll on Windows 2000 not iphlpapi.dll (Windows XP onwards)

https://msdn.microsoft.com/en-us/library/windows/desktop/aa366050(v=vs.85).aspx

**Comment by jschicht** [comment]
AutoIt version 3.3.8.1 was the last one to support Windows 2000. A recompile on that version might do the trick.

**Comment by jschicht** [comment]
Finally a special build ready for use on Windows 2000 / NTFS 3.0. See link in readme.
