### ISSUE TITLE
RawCopy and UAC limitations...

### ISSUE THREAD

**Issue by ofarcis** [jschicht/RawCopy#7]
Hi to all,

When I try to call to RawCopy or RawCopy64, ever appear the UAC message limitation with indication of author not is recognized.  Any solution?

Thanks in advanced, 
Oscar.

**Comment by jschicht** [comment]
Could you explain in more detail how you are calling rawcopy, and the exact
error message, preferrably also with a screenshot?

20. des. 2016 4:59 a.m. skrev "ofarcis" <notifications@github.com>:

**Comment by ofarcis** [comment]
The problem of screenshot is in Spanish. I call to RawCopy normally with the parameters like this:

Dim Command As String = ""
If Environment.Is64BitOperatingSystem = True Then
   Command = Application.StartupPath & "\RawCopy64"
Else
   Command = Application.StartupPath & "\RawCopy"
End If

Dim Parameters As String = "/FileNamePath:" & OriginFile & " /OutputPath:" & Application.StartupPath & "\tmp > msg.txt"
ExecCmd(Command, Parameters)

The problem not necessary is from my development. You can call to RawCopy.exe or RawCopy64.exe with UAC active and ever appear the message that need to press YES because the Authot is unkonw.

Regards, Oscar.

**Comment by ofarcis** [comment]
I need to call to RawCopy without user interventation.

Regards, Oscar.

**Comment by ofarcis** [comment]
![rawcopyuacerror](https://cloud.githubusercontent.com/assets/23546900/21356334/8f76ba82-c6d1-11e6-9073-00410367f0aa.jpg)

This is the error in Widnows spanish.

Regards, Oscar.

**Comment by ofarcis** [comment]
Translate is approximately:

Do you want to allow this application from an unknown advertiser to make changes to the computer?

Regards, Oscar.

**Comment by jschicht** [comment]
What version of Windows are you running?

**Comment by ofarcis** [comment]
Windows server 2016.

Regards, Oscar.

2016-12-20 17:36 GMT+01:00 Joakim Schicht <notifications@github.com>:

**Comment by ofarcis** [comment]
But probably is use any Windows that include UAC present the same problem.

 

Regards, Oscar.

 

 

 

De: Joakim Schicht [mailto:notifications@github.com] 
Enviado el: martes, 20 de diciembre de 2016 17:37
Para: jschicht/RawCopy
CC: ofarcis; Author
Asunto: Re: [jschicht/RawCopy] RawCopy and UAC limitations... (#7)

 

What version of Windows are you running?

**Comment by jschicht** [comment]
I think I never tested the program on Windows Server 2016 yet. You will anyway have to make sure the program is run as administrator. This is because rawcopy is doing lowlevel reading directly from the physical device, where you can ultimately copy any file from the volume regardless of permissions that are set. When I get a chance, I can test more on newest Windows version (10 and Server 2016), to see if there is something new that are interefering.

**Comment by ofarcis** [comment]
I call from a program development in .net. This program run as
administrator right but inside of this, when detect that any file is opened
call to RawCopy or RawCopy64 to make one copy and open from the
application. I think this is the problem, The application have
administration right but the RawCopy not.

Thanks for all.
Regards, Oscar.

2016-12-20 17:50 GMT+01:00 Joakim Schicht <notifications@github.com>:

**Comment by ruchirarya** [comment]
So the issue can be closed now. That's what came to my mind at first that rawcopy is prompting UAC, meaning probably it doesn't have admin privileges while execution.

This is not the software issue. It was related to limited privileges granted by the end user while execution.

**Comment by jschicht** [comment]
Not a program bug.

**Comment by pipkoa** [comment]
it's a matter of using the correct syntax. You are not. Consult the program's github page.
