### ISSUE TITLE
Output NT_USER.DAT file is much larger than source NT_USER.DAT

### ISSUE THREAD

**Issue by RedZoan** [jschicht/RawCopy#8]
Hey Jschicht,

Awesome program overall, but I seem to be running into an issue while using Windows Management Instrumentation Command-line (WMIC). 

I have RAWCOPY copied to a local adminshare on a target machine and remotely envoke the command using WMIC. The command appears to execute properly, however, the output file is 231,424KB, when the source NT_USER.dat file is only ~3MB. What's interesting is if I copy another file "NT_USER" file, the output size is the same. IE: if I copy NT_USER.INI which is only ~1KB, the output still is 231,424KB. 

Any idea what might be causing the issue?

For reference the command I use is:

wmic /node:[REMOTE_IP] process call create "cmd.exe /c \\[REMOTEIP]\[ADMINSHARE]\rawcopy.exe /filenamepath:c:\[SOURCEFILEPATH]\NT_USER.DAT /outputpath:\\[REMOTEIP]\[ADMINSHARE]\"

Any help is appreciated!

Thank you.

**Comment by jschicht** [comment]
Can you specify the whole command line as close as possible? If you want to substitute a name, do so like DUMMYFOLDER1, DUMMYFILE1, DUMMYSHARE1, DUMMYIP1. Keep most characters so it is possible to understand what could be wrong. If you don't want to post the information into the publicly visible issue tracker, you can email me directly.

**Comment by RedZoan** [comment]
Certainly can. Here is the command I use, but with a dummy IP & Username:

wmic /node:192.168.1.1 process call create "cmd.exe /c \\192.168.1.1\admin$\RAWCOPY\rawcopy.exe /filenamepath:c:\Users\john.smith\NT_USER.DAT /outputpath:\\192.168.1.1\admin$\RAWCOPY\COPIED\john.smith\"

**Comment by RedZoan** [comment]
Jschicht,

After revisiting my script, and some troubleshooting, I figured out the issue I was having. I was incorrectly calling the "NTUSER.DAT" file "NT_USER.DAT" (which does not exist). 

As expected, RAWCOPY worked flawlessly once I corrected the file name.

Thanks again for making an awesome program.

-Red

**Comment by jschicht** [comment]
Thanks for getting back with that information.
